### ISSUE TITLE
ePMV doesn't open window in C4D2023.2.2

### ISSUE THREAD

**Issue by TK-RN** [corredD/ePMV#14]
Hi, I installed upy-C4D2023.2.0-win.zip, but in C4D2023.2.2, when I click the ePMV plugin no window pops up. The materials load up, though. And autoPACK opens a window too, just no window for ePMV.

**Comment by corredD** [comment]
can you download and place the following file (c4dAdaptor.py) : https://drive.google.com/file/d/1JbFItopDrd6Uu3jWD-XEsQYhkmffz4y2/view?usp=sharing
inside the plugin folder under /plugins/ePMV/mgl64/MGLToolsPckgs/ePMV/cinema4d/.
IF that doesn't work, attach a screenshot of the console after trying to start the plugin so we can see the error message.

**Comment by TK-RN** [comment]
That worked!! Thanks so much for the reply.
